name: Update Repository structure

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  detect-and-update-structure:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          pip install python-dotenv

      - name: Run update script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: ${{ secrets.REPO }}
        run: python .github/scripts/project_structure.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update Repository Structure"
          title: "Automated Repository Structure Update"
          body: "Automated changes by the 'Update Repository structure' workflow."
          branch: "automated-structure-updates"
          delete-branch: true
